http:
  server_port: __PORT__
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - ::1
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - fd00::/8
  ip_ban_enabled: True
  login_attempts_threshold: 5

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://127.0.0.1:__PORT-CONFIGURATOR__
