#!/bin/bash
# to test the functionnality :
# yunohost app remove homeassistant

set -u
source /usr/share/yunohost/helpers

# retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)
port=$(ynh_app_setting_get $app port)
port_configurator=$(ynh_app_setting_get $app port_configurator)

# definie useful vars
final_path="/srv/$app"
data_path="/home/$app/.$app"

# remove metapackage and its dependencies
ynh_remove_app_dependencies

# remove the app directory securely
ynh_secure_remove "$final_path"

# remove the dedicated nginx config
ynh_remove_nginx_config

# remove a directory securely
ynh_secure_remove "$data_path"

# remove systemd service
## for Home Assistant
systemctl disable $app@$app
ynh_secure_remove "/etc/systemd/system/$app@$app.service"
## for Home Assistant configurator
systemctl disable $app-configurator@$app
ynh_secure_remove "/etc/systemd/system/$app-configurator@$app.service"

# remove service from admin panel
## for Home Assistant
if yunohost service status | grep -q $app@$app
then
	echo "Remove $app@$app service"
	yunohost service remove $app@$app
fi
## for Home Assistant configurator
if yunohost service status | grep -q $app-configurator@$app
then
	echo "Remove $app-configurator@$app service"
	yunohost service remove $app-configurator@$app
fi

# delete a system user
ynh_system_user_delete "$app"

# close port
## for Home Assistant
yunohost firewall disallow TCP $port > /dev/null 2>&1
## for Home Assistant configurator
yunohost firewall disallow TCP $port_configurator > /dev/null 2>&1
